name: myune_music
summary: A music player built with Flutter.
description: |
  Myune Music is a music player built with Flutter.
version: 0.8.0
release: 1
group: Applications/Multimedia
license: Apache-2.0
url: https://github.com/xleave/myune_music_material
icon: assets/images/icon/icon.png
